"""Run planning schemas."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from src.api.schemas.dataset import DatasetOutcome, ValidationIssue, WorkflowName


RunPlanStatus = Literal["ready", "not_eligible", "blocked"]
RunPlanStepStatus = Literal["planned", "blocked", "available"]
RunPlanArtifactAvailability = Literal["available", "generated", "missing"]
RunExecutionStatus = Literal["completed"]


class RunPlanRequest(BaseModel):
    """Request a synchronous dry-run plan for a registered dataset workflow."""

    dataset_id: str = Field(min_length=3, max_length=64)
    workflow: WorkflowName
    parameters: dict[str, object] = Field(default_factory=dict)


class RunPlanArtifact(BaseModel):
    """Artifact required or generated by a run plan."""

    name: str
    role: str
    uri: str | None = None
    required: bool = True
    availability: RunPlanArtifactAvailability
    sha256: str | None = None
    bytes: int | None = Field(default=None, ge=0)
    reason: str | None = None


class RunPlanStep(BaseModel):
    """Single deterministic step in a planned workflow."""

    step_id: str
    name: str
    status: RunPlanStepStatus
    inputs: list[str] = Field(default_factory=list)
    outputs: list[str] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)


class RunPlanResponse(BaseModel):
    """Synchronous dry-run response for a workflow run."""

    plan_id: str
    dataset_id: str
    workflow: WorkflowName
    status: RunPlanStatus
    executable: bool
    created_at: str
    validation_outcome: DatasetOutcome
    parameters: dict[str, object] = Field(default_factory=dict)
    blockers: list[ValidationIssue] = Field(default_factory=list)
    warnings: list[ValidationIssue] = Field(default_factory=list)
    required_artifacts: list[RunPlanArtifact] = Field(default_factory=list)
    steps: list[RunPlanStep] = Field(default_factory=list)


class RunExecutionResponse(BaseModel):
    """Synchronous execution response for safe local workflows."""

    execution_id: str
    plan_id: str
    dataset_id: str
    workflow: WorkflowName
    status: RunExecutionStatus
    started_at: str
    completed_at: str
    row_counts: dict[str, int] = Field(default_factory=dict)
    warnings: list[ValidationIssue] = Field(default_factory=list)
    artifacts: list[RunPlanArtifact] = Field(default_factory=list)
